version: "3"
services:
  jupyterhub:
    image: rueberger/janelia_jupyterhub:latest
    container_name: jupyterhub
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - jhub
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  jupyterhub-network:
    external: true
